# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileCopyrightText: 2026 Auto Crop contributors
"""Procedural backgrounds and clutter (ROADMAP M1.33).

Every background is generated here from a seed: wood, fabric, stone, plain desks, tile, a dark
cutting mat and a white desk (the white-on-white hard case). There are no photographs and no
downloaded textures (the Describable Textures Dataset is excluded: licence), so each background's
licence is that of this project, recorded per image in the manifest as ``background_licence``.

Clutter is a handful of objects (books, boxes, cups, keyboards, pens and extra sheets of nearly
white paper) drawn on the desk *under* the page, so the page outline is always unambiguous in the
ground truth while a detector still has things to confuse it with.
"""

from __future__ import annotations

import math

import cv2
import numpy as np

LICENCE = "MIT OR Apache-2.0 (procedural, generated by tools/synth)"
KINDS = ("wood", "fabric", "stone", "plain", "tile", "dark-mat", "white-desk")


def fbm(rng, h: int, w: int, octaves: int = 5, base: int = 3, persistence: float = 0.55) -> np.ndarray:
    """Fractal value noise in 0..1 (float32), made of upscaled random grids."""
    out = np.zeros((h, w), dtype=np.float32)
    amp, total = 1.0, 0.0
    for o in range(octaves):
        n = base * 2**o
        gh, gw = max(2, round(n * h / max(h, w))) + 1, max(2, round(n * w / max(h, w))) + 1
        grid = rng.random((gh, gw)).astype(np.float32)
        out += amp * cv2.resize(grid, (w, h), interpolation=cv2.INTER_CUBIC)
        total += amp
        amp *= persistence
    out /= total
    lo, hi = float(out.min()), float(out.max())
    return (out - lo) / max(hi - lo, 1e-6)


def _rgb(rng, lo, hi) -> np.ndarray:
    return np.array([rng.uniform(lo[i], hi[i]) for i in range(3)], dtype=np.float32)


def _tint(base: np.ndarray, tex: np.ndarray, contrast: float) -> np.ndarray:
    return np.clip(base[None, None, :] * (1.0 + contrast * (tex[..., None] - 0.5)), 0, 255)


def wood(rng, h, w):
    ang = rng.uniform(0, math.pi)
    yy, xx = np.mgrid[0:h, 0:w].astype(np.float32)
    u = (xx * math.cos(ang) + yy * math.sin(ang)) / max(h, w)
    v = (-xx * math.sin(ang) + yy * math.cos(ang)) / max(h, w)
    warp = fbm(rng, h, w, 4, 3)
    rings = 0.5 + 0.5 * np.sin(2 * math.pi * (v * rng.uniform(6, 14) + 3.0 * warp + 0.6 * u))
    grain = fbm(rng, h, w, 3, 24)
    tex = 0.65 * rings + 0.35 * grain
    c1 = _rgb(rng, (120, 70, 35), (200, 150, 95))
    return _tint(c1, tex, 0.55)


def fabric(rng, h, w):
    yy, xx = np.mgrid[0:h, 0:w].astype(np.float32)
    f = rng.uniform(0.6, 1.4)
    weave = 0.5 + 0.25 * np.sin(xx * f) * np.sin(yy * f) + 0.25 * np.sin(xx * f * 0.5 + yy * 0.3)
    tex = 0.6 * weave + 0.4 * fbm(rng, h, w, 4, 5)
    base = _rgb(rng, (60, 60, 60), (200, 200, 200))
    tint = rng.uniform(0.9, 1.1, size=3).astype(np.float32)
    return _tint(base * tint, tex, 0.5)


def stone(rng, h, w):
    n = fbm(rng, h, w, 6, 3)
    veins = 1.0 - np.abs(2 * fbm(rng, h, w, 5, 4) - 1.0) ** 0.35
    tex = 0.6 * n + 0.4 * veins
    base = _rgb(rng, (110, 105, 100), (210, 205, 195))
    return _tint(base, tex, 0.5)


def plain(rng, h, w):
    base = _rgb(rng, (60, 60, 60), (215, 215, 215)) * rng.uniform(0.93, 1.07, size=3).astype(np.float32)
    return _tint(base, fbm(rng, h, w, 3, 2), 0.18)


def tile(rng, h, w):
    size = int(max(h, w) * rng.uniform(0.10, 0.22))
    yy, xx = np.mgrid[0:h, 0:w]
    ox, oy = int(rng.integers(0, size)), int(rng.integers(0, size))
    cx, cy = (xx + ox) // size, (yy + oy) // size
    shade = (np.sin(cx * 12.9898 + cy * 78.233 + float(rng.uniform(0, 100))) * 43758.5453) % 1.0
    local = fbm(rng, h, w, 3, 6)
    tex = 0.35 * shade.astype(np.float32) + 0.65 * local
    base = _rgb(rng, (130, 130, 130), (225, 225, 220))
    img = _tint(base, tex, 0.30)
    gx = ((xx + ox) % size) < max(2, size // 30)
    gy = ((yy + oy) % size) < max(2, size // 30)
    grout = _rgb(rng, (70, 70, 70), (150, 150, 150))
    img[gx | gy] = grout
    return img


def dark_mat(rng, h, w):
    base = _rgb(rng, (28, 34, 30), (65, 72, 66))
    img = _tint(base, fbm(rng, h, w, 3, 3), 0.12)
    step = max(6, int(max(h, w) / rng.integers(14, 24)))
    yy, xx = np.mgrid[0:h, 0:w]
    lines = ((xx % step) == 0) | ((yy % step) == 0)
    img[lines] = np.clip(img[lines] * 1.6 + 10, 0, 255)
    return img


def white_desk(rng, h, w):
    base = _rgb(rng, (222, 222, 222), (246, 246, 246)) * rng.uniform(0.98, 1.02, size=3).astype(np.float32)
    return _tint(base, fbm(rng, h, w, 4, 3), 0.07)


_MAKERS = {
    "wood": wood,
    "fabric": fabric,
    "stone": stone,
    "plain": plain,
    "tile": tile,
    "dark-mat": dark_mat,
    "white-desk": white_desk,
}


# --- Training-only desks (see `trainset`): textures the evaluation suites do not use. They add
# parallel plank gaps and veins that look like page edges, and busy speckle, to teach a learned
# detector that desk texture is not a page. Registered below the defaults, never drawn by them.


def planks(rng, h, w):
    """Wood planks with dark gaps and a different tone per plank (long parallel false edges)."""
    ang = rng.uniform(0, math.pi)
    yy, xx = np.mgrid[0:h, 0:w].astype(np.float32)
    u = (xx * math.cos(ang) + yy * math.sin(ang)) / max(h, w)
    v = (-xx * math.sin(ang) + yy * math.cos(ang)) / max(h, w)
    width = float(rng.uniform(0.07, 0.2))
    off = float(rng.uniform(0, width))
    idx = np.floor((v + off) / width)
    tone = (np.sin(idx * 12.9898 + float(rng.uniform(0, 100))) * 43758.5453) % 1.0
    grain = fbm(rng, h, w, 3, 28)
    streak = 0.5 + 0.5 * np.sin(2 * math.pi * (u * rng.uniform(1.5, 4.0) + 2.0 * fbm(rng, h, w, 3, 3)))
    tex = 0.4 * tone.astype(np.float32) + 0.3 * grain + 0.3 * streak
    base = _rgb(rng, (100, 60, 30), (210, 165, 110))
    img = _tint(base, tex, 0.6)
    frac = ((v + off) / width) % 1.0
    gap = (frac < 0.012) | (frac > 0.988)
    img[gap] = img[gap] * float(rng.uniform(0.25, 0.5))
    return img


def marble(rng, h, w):
    """Bright polished stone with sharp dark veins."""
    n = fbm(rng, h, w, 6, 2)
    veins = np.abs(np.sin(8.0 * math.pi * (fbm(rng, h, w, 5, 2) + 0.35 * n)))
    veins = veins ** float(rng.uniform(6, 18))
    base = _rgb(rng, (190, 190, 185), (240, 238, 232))
    img = _tint(base, n, 0.10)
    return np.clip(img * (1.0 - float(rng.uniform(0.3, 0.6)) * veins[..., None]), 0, 255)


def terrazzo(rng, h, w):
    """Light cement with random coloured chips: busy speckle at every scale."""
    base = _rgb(rng, (170, 165, 155), (235, 232, 225))
    img = _tint(base, fbm(rng, h, w, 3, 3), 0.12)
    scale = max(h, w)
    for _ in range(int(rng.integers(120, 360))):
        cx, cy = float(rng.uniform(0, w)), float(rng.uniform(0, h))
        r = scale * float(rng.uniform(0.004, 0.02))
        col = tuple(float(c) for c in rng.uniform(40, 220, size=3))
        pts = np.array([[cx + r * math.cos(a + rng.uniform(-0.4, 0.4)) * rng.uniform(0.6, 1.2), cy + r * math.sin(a + rng.uniform(-0.4, 0.4)) * rng.uniform(0.6, 1.2)] for a in np.linspace(0, 2 * math.pi, int(rng.integers(5, 8)), endpoint=False)], dtype=np.float32)
        cv2.fillPoly(img, [np.round(pts).astype(np.int32)], col, lineType=cv2.LINE_AA)
    return img


def carpet(rng, h, w):
    """Dense fibre noise, low contrast and mid brightness (felt, carpet, a sofa)."""
    fine = rng.random((h, w)).astype(np.float32)
    fine = cv2.GaussianBlur(fine, (0, 0), 0.8)
    tex = 0.55 * (fine - fine.min()) / max(float(fine.max() - fine.min()), 1e-6) + 0.45 * fbm(rng, h, w, 4, 4)
    base = _rgb(rng, (50, 50, 50), (210, 205, 200)) * rng.uniform(0.9, 1.1, size=3).astype(np.float32)
    return _tint(base, tex, 0.35)


TRAIN_KINDS = ("planks", "marble", "terrazzo", "carpet")
_MAKERS.update({"planks": planks, "marble": marble, "terrazzo": terrazzo, "carpet": carpet})


def make(kind: str, rng, h: int, w: int) -> np.ndarray:
    """A float32 RGB background (0..255) of ``h x w`` pixels."""
    return _MAKERS[kind](rng, h, w).astype(np.float32)


def _quad(cx, cy, w, h, ang):
    c, s = math.cos(ang), math.sin(ang)
    pts = [(-w / 2, -h / 2), (w / 2, -h / 2), (w / 2, h / 2), (-w / 2, h / 2)]
    return np.array([[cx + x * c - y * s, cy + x * s + y * c] for x, y in pts], dtype=np.float32)


def _shadowed(img, poly, colour, offset, strength, blur):
    """Draw a polygon with a soft drop shadow."""
    h, w = img.shape[:2]
    sh = np.zeros((h, w), dtype=np.float32)
    cv2.fillPoly(sh, [np.round(poly + offset).astype(np.int32)], 1.0)
    sh = cv2.GaussianBlur(sh, (0, 0), blur)
    img *= (1.0 - strength * sh)[..., None]
    cv2.fillPoly(img, [np.round(poly).astype(np.int32)], tuple(float(c) for c in colour), lineType=cv2.LINE_AA)


def add_clutter(img: np.ndarray, rng, level: str, avoid: np.ndarray | None = None) -> list[str]:
    """Draw clutter on ``img`` in place; returns the object kinds drawn (for the manifest)."""
    count = {"none": 0, "light": int(rng.integers(2, 5)), "heavy": int(rng.integers(8, 13))}[level]
    h, w = img.shape[:2]
    scale = max(h, w)
    drawn = []
    for _ in range(count):
        kind = ["book", "box", "cup", "keyboard", "pen", "sheet", "sheet", "plant"][int(rng.integers(8))]
        # Half of the objects crowd the page so they touch or nearly touch its edges.
        if avoid is not None and rng.random() < 0.5:
            c = avoid[int(rng.integers(4))]
            cx = float(c[0] + rng.normal(0, 0.12 * scale))
            cy = float(c[1] + rng.normal(0, 0.12 * scale))
        else:
            cx, cy = float(rng.uniform(0, w)), float(rng.uniform(0, h))
        ang = float(rng.uniform(0, math.pi))
        off = np.array([rng.uniform(2, 7), rng.uniform(3, 9)], dtype=np.float32)
        blur = float(rng.uniform(1.5, 4.5))
        if kind == "sheet":
            tone = float(rng.uniform(225, 250))
            col = (tone, tone, tone - float(rng.uniform(0, 10)))
            poly = _quad(cx, cy, scale * rng.uniform(0.15, 0.4), scale * rng.uniform(0.2, 0.5), ang)
            _shadowed(img, poly, col, off, 0.35, blur)
            # a few faint lines of print so the sheet is not a flat colour
            for k in range(int(rng.integers(3, 8))):
                t = (k + 1) / 9.0
                a = poly[0] * (1 - t) + poly[3] * t + (poly[1] - poly[0]) * 0.12
                b = poly[1] * (1 - t) + poly[2] * t - (poly[1] - poly[0]) * 0.12
                cv2.line(img, tuple(np.round(a).astype(int)), tuple(np.round(b).astype(int)), (tone * 0.72,) * 3, 1, cv2.LINE_AA)
        elif kind in ("book", "box"):
            col = tuple(float(x) for x in rng.uniform(30, 215, size=3))
            poly = _quad(cx, cy, scale * rng.uniform(0.12, 0.35), scale * rng.uniform(0.08, 0.28), ang)
            _shadowed(img, poly, col, off, 0.45, blur)
            cv2.polylines(img, [np.round(poly).astype(np.int32)], True, tuple(c * 0.6 for c in col), 2, cv2.LINE_AA)
        elif kind == "cup":
            r = scale * float(rng.uniform(0.04, 0.11))
            col = tuple(float(x) for x in rng.uniform(40, 235, size=3))
            sh = np.zeros((h, w), dtype=np.float32)
            cv2.circle(sh, (int(cx + off[0]), int(cy + off[1])), int(r), 1.0, -1)
            sh = cv2.GaussianBlur(sh, (0, 0), blur)
            img *= (1.0 - 0.45 * sh)[..., None]
            cv2.circle(img, (int(cx), int(cy)), int(r), col, -1, cv2.LINE_AA)
            cv2.circle(img, (int(cx), int(cy)), int(r * 0.72), tuple(c * 0.8 for c in col), 2, cv2.LINE_AA)
        elif kind == "keyboard":
            col = (35.0, 37.0, 40.0)
            poly = _quad(cx, cy, scale * rng.uniform(0.3, 0.5), scale * rng.uniform(0.09, 0.16), ang)
            _shadowed(img, poly, col, off, 0.4, blur)
            for k in range(1, 6):
                t = k / 6.0
                a = poly[0] * (1 - t) + poly[3] * t
                b = poly[1] * (1 - t) + poly[2] * t
                cv2.line(img, tuple(np.round(a).astype(int)), tuple(np.round(b).astype(int)), (120.0,) * 3, 2, cv2.LINE_AA)
        elif kind == "pen":
            col = tuple(float(x) for x in rng.uniform(10, 200, size=3))
            ln = scale * float(rng.uniform(0.15, 0.35))
            p0 = (cx - math.cos(ang) * ln / 2, cy - math.sin(ang) * ln / 2)
            p1 = (cx + math.cos(ang) * ln / 2, cy + math.sin(ang) * ln / 2)
            cv2.line(img, (round(p0[0] + off[0]), round(p0[1] + off[1])), (round(p1[0] + off[0]), round(p1[1] + off[1])), (0.0, 0.0, 0.0), 5, cv2.LINE_AA)
            cv2.line(img, (round(p0[0]), round(p0[1])), (round(p1[0]), round(p1[1])), col, 4, cv2.LINE_AA)
        else:  # plant: a few green blobs
            for _ in range(int(rng.integers(3, 7))):
                r = int(scale * rng.uniform(0.015, 0.04))
                p = (int(cx + rng.normal(0, scale * 0.04)), int(cy + rng.normal(0, scale * 0.04)))
                cv2.circle(img, p, r, (float(rng.uniform(20, 70)), float(rng.uniform(90, 160)), float(rng.uniform(20, 70))), -1, cv2.LINE_AA)
        drawn.append(kind)
    np.clip(img, 0, 255, out=img)
    return drawn
