# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileCopyrightText: 2026 Auto Crop contributors
"""Linear barcodes and QR codes as boolean module grids (ROADMAP M1.31).

``python-barcode`` (MIT) builds the Code 128 and EAN-13 bar patterns and ``segno`` (BSD-3-Clause)
builds QR matrices; both only supply the module pattern, the pixels are drawn here. The payloads are
random digits generated by this project.
"""

from __future__ import annotations

import barcode
import numpy as np
import segno


def code128_modules(payload: str) -> np.ndarray:
    """Bar pattern of a Code 128 symbol: 1-D bool array, True = dark."""
    pattern = barcode.get("code128", payload).build()[0]
    return np.array([c == "1" for c in pattern], dtype=bool)


def ean13_modules(twelve_digits: str) -> np.ndarray:
    """Bar pattern of an EAN-13 symbol (the check digit is computed): True = dark."""
    pattern = barcode.get("ean13", twelve_digits).build()[0]
    return np.array([c == "1" for c in pattern], dtype=bool)


def qr_modules(payload: str) -> np.ndarray:
    """QR matrix (without quiet zone): 2-D bool array, True = dark."""
    qr = segno.make(payload, error="m", micro=False)
    return np.array([[bool(v) for v in row] for row in qr.matrix], dtype=bool)


def draw_linear(modules: np.ndarray, module_px: int, height_px: int, quiet: int = 10) -> np.ndarray:
    """A uint8 image (255 = ink) of a linear symbol with quiet zones on both sides."""
    row = np.repeat(modules, module_px)
    pad = np.zeros(quiet * module_px, dtype=bool)
    row = np.concatenate([pad, row, pad])
    return np.tile(row.astype(np.uint8) * 255, (height_px, 1))


def draw_qr(modules: np.ndarray, module_px: int, quiet: int = 4) -> np.ndarray:
    """A uint8 image (255 = ink) of a QR symbol with its quiet zone."""
    big = np.kron(modules.astype(np.uint8) * 255, np.ones((module_px, module_px), dtype=np.uint8))
    q = quiet * module_px
    return np.pad(big, q, constant_values=0)
