# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileCopyrightText: 2026 Auto Crop contributors
"""A Display P3 ICC profile written from the primaries, and the sRGB to P3 pixel conversion.

The profile is a small ICC v2 matrix/TRC display profile built here from published chromaticities
(DCI-P3 primaries, D65 white point, sRGB transfer curve), chromatically adapted to the D50 PCS with
the Bradford matrix. It is generated data with no third-party copyright (no Apple or other vendor
profile is copied), and it is byte-for-byte reproducible: the header carries a fixed date.
"""

from __future__ import annotations

import struct
from functools import lru_cache

import numpy as np

P3_PRIMARIES = {"r": (0.680, 0.320), "g": (0.265, 0.690), "b": (0.150, 0.060)}
SRGB_PRIMARIES = {"r": (0.640, 0.330), "g": (0.300, 0.600), "b": (0.150, 0.060)}
D65 = (0.3127, 0.3290)
D50_XYZ = np.array([0.9642, 1.0, 0.8249])
BRADFORD = np.array([[0.8951, 0.2664, -0.1614], [-0.7502, 1.7135, 0.0367], [0.0389, -0.0685, 1.0296]])


def _xyz(xy) -> np.ndarray:
    x, y = xy
    return np.array([x / y, 1.0, (1 - x - y) / y])


def rgb_to_xyz_matrix(primaries: dict, white_xy) -> np.ndarray:
    """Linear RGB to XYZ (white point ``white_xy``) for the given primaries."""
    p = np.column_stack([_xyz(primaries[c]) for c in "rgb"])
    s = np.linalg.solve(p, _xyz(white_xy))
    return p * s[None, :]


def _adapt_to_d50(white_xy) -> np.ndarray:
    src, dst = BRADFORD @ _xyz(white_xy), BRADFORD @ D50_XYZ
    return np.linalg.inv(BRADFORD) @ np.diag(dst / src) @ BRADFORD


def srgb_eotf(v: np.ndarray) -> np.ndarray:
    v = np.asarray(v, dtype=np.float64)
    return np.where(v <= 0.04045, v / 12.92, ((v + 0.055) / 1.055) ** 2.4)


def srgb_oetf(v: np.ndarray) -> np.ndarray:
    v = np.clip(np.asarray(v, dtype=np.float64), 0.0, 1.0)
    return np.where(v <= 0.0031308, v * 12.92, 1.055 * v ** (1 / 2.4) - 0.055)


def srgb_to_p3_matrix() -> np.ndarray:
    """Linear sRGB (D65) to linear Display P3 (D65)."""
    return np.linalg.inv(rgb_to_xyz_matrix(P3_PRIMARIES, D65)) @ rgb_to_xyz_matrix(SRGB_PRIMARIES, D65)


def srgb_to_p3(rgb: np.ndarray) -> np.ndarray:
    """uint8 sRGB pixels to the uint8 values that show the same colours in Display P3."""
    lin = srgb_eotf(rgb.astype(np.float64) / 255.0)
    out = lin @ srgb_to_p3_matrix().T
    return np.clip(np.rint(srgb_oetf(out) * 255.0), 0, 255).astype(np.uint8)


def _s15(v: float) -> bytes:
    return struct.pack(">i", int(round(v * 65536.0)))


def _xyz_tag(v) -> bytes:
    return b"XYZ \x00\x00\x00\x00" + b"".join(_s15(float(c)) for c in v)


def _text_desc(s: str) -> bytes:
    a = s.encode("ascii") + b"\x00"
    return b"desc\x00\x00\x00\x00" + struct.pack(">I", len(a)) + a + struct.pack(">II", 0, 0) + struct.pack(">HB", 0, 0) + b"\x00" * 67


def _text(s: str) -> bytes:
    return b"text\x00\x00\x00\x00" + s.encode("ascii") + b"\x00"


def _curv(n: int = 1024) -> bytes:
    xs = np.linspace(0.0, 1.0, n)
    vals = np.clip(np.rint(srgb_eotf(xs) * 65535.0), 0, 65535).astype(">u2")
    return b"curv\x00\x00\x00\x00" + struct.pack(">I", n) + vals.tobytes()


def _matrix_profile(primaries: dict, description: str) -> bytes:
    """A v2.4 matrix/TRC display profile (D50 PCS, sRGB transfer curve) for ``primaries``."""
    to_pcs = _adapt_to_d50(D65) @ rgb_to_xyz_matrix(primaries, D65)
    trc = _curv()
    tags = [
        (b"desc", _text_desc(description)),
        (b"cprt", _text("Generated by tools/synth; no copyright claimed (CC0-1.0)")),
        (b"wtpt", _xyz_tag(D50_XYZ)),
        (b"rXYZ", _xyz_tag(to_pcs[:, 0])),
        (b"gXYZ", _xyz_tag(to_pcs[:, 1])),
        (b"bXYZ", _xyz_tag(to_pcs[:, 2])),
        (b"rTRC", trc),
        (b"gTRC", trc),
        (b"bTRC", trc),
    ]
    table_len = 4 + 12 * len(tags)
    offset = 128 + table_len
    table, body = b"", b""
    cache: dict[bytes, int] = {}
    for sig, data in tags:
        if data in cache:  # identical tags (the three curves) share one block
            off = cache[data]
        else:
            off = offset + len(body)
            cache[data] = off
            body += data + b"\x00" * (-len(data) % 4)
        table += sig + struct.pack(">II", off, len(data))
    size = 128 + table_len + len(body)
    header = struct.pack(">I4sI4s4s4s", size, b"\x00\x00\x00\x00", 0x02400000, b"mntr", b"RGB ", b"XYZ ")
    header += struct.pack(">6H", 2026, 10, 3, 0, 0, 0)  # fixed date: reproducible bytes
    header += b"acsp" + b"\x00" * 4 + struct.pack(">I", 0) + b"\x00" * 4 + b"\x00" * 4 + b"\x00" * 8
    header += struct.pack(">I", 0) + b"".join(_s15(float(c)) for c in D50_XYZ) + b"\x00" * 4 + b"\x00" * 16 + b"\x00" * 28
    assert len(header) == 128, len(header)
    return header + struct.pack(">I", len(tags)) + table + body


@lru_cache(maxsize=1)
def display_p3_profile() -> bytes:
    """The Display P3 profile."""
    return _matrix_profile(P3_PRIMARIES, "Display P3 (Auto Crop synth)")


@lru_cache(maxsize=1)
def srgb_profile() -> bytes:
    """An sRGB profile written the same way (LittleCMS's own `createProfile` stamps the current
    time into the header, which would make the output bytes differ from run to run)."""
    return _matrix_profile(SRGB_PRIMARIES, "sRGB (Auto Crop synth)")
