// SPDX-License-Identifier: MIT OR Apache-2.0
// SPDX-FileCopyrightText: 2026 Auto Crop contributors

//! `cargo xtask provenance [--render]` (ROADMAP M0.25, M1.74).
//!
//! Validates `docs/policy/provenance/provenance.jsonl` (the source of truth) and
//! generates `provenance.csv` and `provenance.md` from it. Without `--render` the
//! generated views must already be up to date (so a hand edit or a stale view
//! fails CI). It also checks that the human-written register `docs/provenance.md` covers every
//! native library, pinned Python tool, font package and provenance-log entry (see `register`).

use std::fs;

const DIR: &str = "docs/policy/provenance";
const FIELDS: &[&str] = &[
    "id",
    "kind",
    "name",
    "source_url",
    "licence_url",
    "spdx",
    "retrieved",
    "sha256",
    "allowed_use",
    "attribution",
    "init_source",
    "reviewer",
    "status",
    "notes",
];
const STATUSES: &[&str] = &["cleared", "pending", "blocked", "banned", "exception"];
const KINDS: &[&str] = &["dataset", "weights", "code", "font", "texture"];

pub type Row = Vec<String>;

/// Parses and validates the JSON-lines text; returns rows in `FIELDS` order.
pub fn parse(text: &str) -> Result<Vec<Row>, String> {
    let mut rows = Vec::new();
    let mut ids = std::collections::HashSet::new();
    for (i, line) in text
        .lines()
        .enumerate()
        .filter(|(_, l)| !l.trim().is_empty())
    {
        let n = i + 1;
        let v: serde_json::Value =
            serde_json::from_str(line).map_err(|e| format!("line {n}: {e}"))?;
        let obj = v.as_object().ok_or(format!("line {n}: not an object"))?;
        for k in obj.keys() {
            if !FIELDS.contains(&k.as_str()) {
                return Err(format!("line {n}: unknown field `{k}`"));
            }
        }
        let mut row = Vec::new();
        for f in FIELDS {
            let s = obj
                .get(*f)
                .and_then(|x| x.as_str())
                .ok_or(format!("line {n}: missing string field `{f}`"))?;
            row.push(s.to_owned());
        }
        let get = |name: &str| row[FIELDS.iter().position(|f| *f == name).unwrap_or(0)].clone();
        if !STATUSES.contains(&get("status").as_str()) {
            return Err(format!("line {n}: bad status `{}`", get("status")));
        }
        if !KINDS.contains(&get("kind").as_str()) {
            return Err(format!("line {n}: bad kind `{}`", get("kind")));
        }
        if get("licence_url").is_empty() || get("spdx").is_empty() {
            return Err(format!("line {n}: `licence_url` and `spdx` are required"));
        }
        if !ids.insert(get("id")) {
            return Err(format!("line {n}: duplicate id `{}`", get("id")));
        }
        rows.push(row);
    }
    if rows.is_empty() {
        return Err("the provenance log has no rows".to_owned());
    }
    Ok(rows)
}

fn csv_cell(s: &str) -> String {
    format!("\"{}\"", s.replace('"', "\"\""))
}

pub fn render_csv(rows: &[Row]) -> String {
    let mut out = FIELDS.join(",");
    out.push('\n');
    for r in rows {
        out.push_str(&r.iter().map(|c| csv_cell(c)).collect::<Vec<_>>().join(","));
        out.push('\n');
    }
    out
}

pub fn render_md(rows: &[Row]) -> String {
    let idx = |name: &str| FIELDS.iter().position(|f| *f == name).unwrap_or(0);
    let mut out = String::from(
        "<!-- Generated by `cargo xtask provenance --render` from provenance.jsonl. Do not edit. -->\n\n# Provenance log (generated view)\n\n| Status | Id | Kind | SPDX | Allowed use | Licence | Notes |\n|---|---|---|---|---|---|---|\n",
    );
    for r in rows {
        out.push_str(&format!(
            "| {} | `{}` | {} | {} | {} | [link]({}) | {} |\n",
            r[idx("status")],
            r[idx("id")],
            r[idx("kind")],
            r[idx("spdx")],
            r[idx("allowed_use")],
            r[idx("licence_url")],
            r[idx("notes")].replace('|', "/")
        ));
    }
    out
}

pub fn run(args: &[String]) -> Result<(), String> {
    let render = args.iter().any(|a| a == "--render");
    let text = fs::read_to_string(format!("{DIR}/provenance.jsonl"))
        .map_err(|e| format!("provenance.jsonl: {e}"))?;
    let rows = parse(&text)?;
    let (csv, md) = (render_csv(&rows), render_md(&rows));
    let (csv_path, md_path) = (
        format!("{DIR}/provenance.csv"),
        format!("{DIR}/provenance.md"),
    );
    if render {
        fs::write(&csv_path, csv).map_err(|e| e.to_string())?;
        fs::write(&md_path, md).map_err(|e| e.to_string())?;
        println!("provenance: rendered {} rows", rows.len());
        return Ok(());
    }
    let stale = |p: &str, want: &str| {
        fs::read_to_string(p)
            .map(|t| t.replace("\r\n", "\n") != want)
            .unwrap_or(true)
    };
    if stale(&csv_path, &csv) || stale(&md_path, &md) {
        return Err(
            "generated provenance views are stale: run `cargo xtask provenance --render`"
                .to_owned(),
        );
    }
    let ids: Vec<String> = rows.iter().map(|r| r[0].clone()).collect();
    let register = crate::register::check_repo(&ids)?;
    if !register.is_empty() {
        return Err(register.join(
            "
",
        ));
    }
    println!(
        "provenance: {} rows valid, views up to date, docs/provenance.md register complete",
        rows.len()
    );
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn line(id: &str, status: &str) -> String {
        format!(
            "{{\"id\":\"{id}\",\"kind\":\"dataset\",\"name\":\"n\",\"source_url\":\"u\",\"licence_url\":\"l\",\"spdx\":\"MIT\",\"retrieved\":\"2026-01-01\",\"sha256\":\"\",\"allowed_use\":\"x\",\"attribution\":\"\",\"init_source\":\"\",\"reviewer\":\"\",\"status\":\"{status}\",\"notes\":\"a|b\"}}"
        )
    }

    #[test]
    fn valid_rows_parse_and_render() {
        let rows = parse(&format!(
            "{}\n{}\n",
            line("a", "cleared"),
            line("b", "banned")
        ))
        .unwrap();
        assert_eq!(rows.len(), 2);
        assert!(render_csv(&rows).starts_with("id,kind,name"));
        assert!(render_md(&rows).contains("a/b"));
    }

    #[test]
    fn bad_status_duplicate_and_unknown_fields_fail() {
        assert!(parse(&line("a", "maybe")).is_err());
        assert!(
            parse(&format!(
                "{}\n{}",
                line("a", "cleared"),
                line("a", "cleared")
            ))
            .is_err()
        );
        assert!(parse(&line("a", "cleared").replace("\"id\"", "\"idx\"")).is_err());
    }

    #[test]
    fn real_seed_log_is_valid() {
        let text = fs::read_to_string("../docs/policy/provenance/provenance.jsonl").unwrap();
        let rows = parse(&text).unwrap();
        assert!(rows.len() >= 10);
    }
}
